// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for `ListAuthTokens`.
public struct ListAuthTokensRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent to list auth tokens from.
  /// Format:
  /// projects/{project}/locations/{location}/instances/{instance}/tokenAuthUsers/{token_auth_user}
  public var parent: Swift.String = Swift.String()

  /// Optional. The maximum number of items to return. The maximum value is 1000;
  /// values above 1000 will be coerced to 1000.
  ///
  /// If not specified, a default value of 1000 will be used by the service.
  /// Regardless of the page_size value, the response may include a partial list
  /// and a caller should only rely on response's
  /// `next_page_token`
  /// to determine if there are more auth tokens left to be queried.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. The `next_page_token` value returned from a previous
  /// `ListAuthTokens` request, if any.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. Expression for filtering results.
  public var filter: Swift.String = Swift.String()

  /// Optional. Sort results by a defined order.
  public var orderBy: Swift.String = Swift.String()

  /// Initialize a new instance of `ListAuthTokensRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListAuthTokensRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.memorystore.v1.ListAuthTokensRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
