// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongrunning
import GoogleRpc
import GoogleCloudGax

/// Service describing handlers for resources
///
/// @Snippet(path: "MemorystoreQuickstart")
public class MemorystoreClient: Clients.MemorystoreProtocol {
  let inner: any Clients.MemorystoreStub

  /// Creates a new `MemorystoreClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.MemorystoreStub = try Clients.MemorystoreTransport(options)
    inner = Clients.MemorystoreRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.MemorystoreLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists Instances in a given project and location.
  ///
  /// @Snippet(path: "Memorystore_ListInstances")
  public func listInstances(
    request: ListInstancesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMemorystoreV1.ListInstancesResponse {
    try await self.inner.listInstances(request: request, options: options)
  }

  /// Lists Instances in a given project and location.
  ///
  /// @Snippet(path: "Memorystore_ListInstances")
  public func listInstances(
    byItem: ListInstancesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Instance, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudMemorystoreV1.ListInstancesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listInstances(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single Instance.
  ///
  /// @Snippet(path: "Memorystore_GetInstance")
  public func getInstance(
    request: GetInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMemorystoreV1.Instance {
    try await self.inner.getInstance(request: request, options: options)
  }

  /// Creates a new Instance in a given project and location.
  ///
  /// @Snippet(path: "Memorystore_CreateInstance")
  public func createInstance(
    request: CreateInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.createInstance(request: request, options: options)
  }

  /// Creates a new Instance in a given project and location.
  ///
  /// @Snippet(path: "Memorystore_CreateInstance")
  public func createInstance(
    withPolling: CreateInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Instance> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Instance>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Instance(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createInstance(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Updates the parameters of a single Instance.
  ///
  /// @Snippet(path: "Memorystore_UpdateInstance")
  public func updateInstance(
    request: UpdateInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.updateInstance(request: request, options: options)
  }

  /// Updates the parameters of a single Instance.
  ///
  /// @Snippet(path: "Memorystore_UpdateInstance")
  public func updateInstance(
    withPolling: UpdateInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Instance> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Instance>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Instance(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.updateInstance(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Deletes a single Instance.
  ///
  /// @Snippet(path: "Memorystore_DeleteInstance")
  public func deleteInstance(
    request: DeleteInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.deleteInstance(request: request, options: options)
  }

  /// Deletes a single Instance.
  ///
  /// @Snippet(path: "Memorystore_DeleteInstance")
  public func deleteInstance(
    withPolling: DeleteInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Void>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response:
        return .init(done: true, result: .success(()))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.deleteInstance(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Gets details about the certificate authority for an Instance.
  ///
  /// @Snippet(path: "Memorystore_GetCertificateAuthority")
  public func getCertificateAuthority(
    request: GetCertificateAuthorityRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMemorystoreV1.CertificateAuthority {
    try await self.inner.getCertificateAuthority(request: request, options: options)
  }

  /// Gets the details of shared regional certificate authority information for
  /// Memorystore instance.
  ///
  /// @Snippet(path: "Memorystore_GetSharedRegionalCertificateAuthority")
  public func getSharedRegionalCertificateAuthority(
    request: GetSharedRegionalCertificateAuthorityRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMemorystoreV1.SharedRegionalCertificateAuthority {
    try await self.inner.getSharedRegionalCertificateAuthority(request: request, options: options)
  }

  /// Reschedules upcoming maintenance event.
  ///
  /// @Snippet(path: "Memorystore_RescheduleMaintenance")
  public func rescheduleMaintenance(
    request: RescheduleMaintenanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.rescheduleMaintenance(request: request, options: options)
  }

  /// Reschedules upcoming maintenance event.
  ///
  /// @Snippet(path: "Memorystore_RescheduleMaintenance")
  public func rescheduleMaintenance(
    withPolling: RescheduleMaintenanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Instance> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Instance>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Instance(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.rescheduleMaintenance(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Lists all backup collections owned by a consumer project in either the
  /// specified location (region) or all locations.
  ///
  /// If `location_id` is specified as `-` (wildcard), then all regions
  /// available to the project are queried, and the results are aggregated.
  ///
  /// @Snippet(path: "Memorystore_ListBackupCollections")
  public func listBackupCollections(
    request: ListBackupCollectionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMemorystoreV1.ListBackupCollectionsResponse {
    try await self.inner.listBackupCollections(request: request, options: options)
  }

  /// Lists all backup collections owned by a consumer project in either the
  /// specified location (region) or all locations.
  ///
  /// If `location_id` is specified as `-` (wildcard), then all regions
  /// available to the project are queried, and the results are aggregated.
  ///
  /// @Snippet(path: "Memorystore_ListBackupCollections")
  public func listBackupCollections(
    byItem: ListBackupCollectionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<BackupCollection, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudMemorystoreV1.ListBackupCollectionsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listBackupCollections(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Get a backup collection.
  ///
  /// @Snippet(path: "Memorystore_GetBackupCollection")
  public func getBackupCollection(
    request: GetBackupCollectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMemorystoreV1.BackupCollection {
    try await self.inner.getBackupCollection(request: request, options: options)
  }

  /// Lists all backups owned by a backup collection.
  ///
  /// @Snippet(path: "Memorystore_ListBackups")
  public func listBackups(
    request: ListBackupsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMemorystoreV1.ListBackupsResponse {
    try await self.inner.listBackups(request: request, options: options)
  }

  /// Lists all backups owned by a backup collection.
  ///
  /// @Snippet(path: "Memorystore_ListBackups")
  public func listBackups(
    byItem: ListBackupsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Backup, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudMemorystoreV1.ListBackupsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listBackups(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets the details of a specific backup.
  ///
  /// @Snippet(path: "Memorystore_GetBackup")
  public func getBackup(
    request: GetBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMemorystoreV1.Backup {
    try await self.inner.getBackup(request: request, options: options)
  }

  /// Deletes a specific backup.
  ///
  /// @Snippet(path: "Memorystore_DeleteBackup")
  public func deleteBackup(
    request: DeleteBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.deleteBackup(request: request, options: options)
  }

  /// Deletes a specific backup.
  ///
  /// @Snippet(path: "Memorystore_DeleteBackup")
  public func deleteBackup(
    withPolling: DeleteBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Void>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response:
        return .init(done: true, result: .success(()))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.deleteBackup(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Exports a specific backup to a customer target Cloud Storage URI.
  ///
  /// @Snippet(path: "Memorystore_ExportBackup")
  public func exportBackup(
    request: ExportBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.exportBackup(request: request, options: options)
  }

  /// Exports a specific backup to a customer target Cloud Storage URI.
  ///
  /// @Snippet(path: "Memorystore_ExportBackup")
  public func exportBackup(
    withPolling: ExportBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Backup> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Backup>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Backup(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.exportBackup(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Backup>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Backup Instance.
  /// If this is the first time a backup is being created, a backup collection
  /// will be created at the backend, and this backup belongs to this collection.
  /// Both collection and backup will have a resource name. Backup will be
  /// executed for each shard. A replica (primary if nonHA) will be selected to
  /// perform the execution. Backup call will be rejected if there is an ongoing
  /// backup or update operation. Be aware that during preview, if the instance's
  /// internal software version is too old, critical update will be performed
  /// before actual backup. Once the internal software version is updated to the
  /// minimum version required by the backup feature, subsequent backups will not
  /// require critical update. After preview, there will be no critical update
  /// needed for backup.
  ///
  /// @Snippet(path: "Memorystore_BackupInstance")
  public func backupInstance(
    request: BackupInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.backupInstance(request: request, options: options)
  }

  /// Backup Instance.
  /// If this is the first time a backup is being created, a backup collection
  /// will be created at the backend, and this backup belongs to this collection.
  /// Both collection and backup will have a resource name. Backup will be
  /// executed for each shard. A replica (primary if nonHA) will be selected to
  /// perform the execution. Backup call will be rejected if there is an ongoing
  /// backup or update operation. Be aware that during preview, if the instance's
  /// internal software version is too old, critical update will be performed
  /// before actual backup. Once the internal software version is updated to the
  /// minimum version required by the backup feature, subsequent backups will not
  /// require critical update. After preview, there will be no critical update
  /// needed for backup.
  ///
  /// @Snippet(path: "Memorystore_BackupInstance")
  public func backupInstance(
    withPolling: BackupInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Instance> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Instance>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Instance(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.backupInstance(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "Memorystore_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "Memorystore_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "Memorystore_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Memorystore_ListOperations")
  public func listOperations(
    request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Memorystore_ListOperations")
  public func listOperations(
    byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongrunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Memorystore_GetOperation")
  func getOperation(
    request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Memorystore_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongrunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Memorystore_CancelOperation")
  public func cancelOperation(
    request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `MemorystoreClient`.
  ///
  /// To mock `MemorystoreClient` change your functions to receive
  /// `some MemorystoreProtocol` or `any MemorystoreProtocol`
  /// and pass a mock implementation in your tests.
  public protocol MemorystoreProtocol {
    /// See `MemorystoreClient.listInstances`.
    func listInstances(request: ListInstancesRequest) async throws
      -> GoogleCloudMemorystoreV1.ListInstancesResponse

    /// See `MemorystoreClient.listInstances`.
    func listInstances(
      byItem: ListInstancesRequest
    ) throws -> any AsyncSequence<Instance, Swift.Error>

    /// See `MemorystoreClient.listInstances`.
    func listInstances(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Instance, Swift.Error>

    /// See `MemorystoreClient.getInstance`.
    func getInstance(request: GetInstanceRequest) async throws -> GoogleCloudMemorystoreV1.Instance

    /// See `MemorystoreClient.getInstance`.
    func getInstance(
      name: Swift.String,
    ) async throws -> GoogleCloudMemorystoreV1.Instance

    /// See `MemorystoreClient.createInstance`.
    func createInstance(request: CreateInstanceRequest) async throws -> GoogleLongrunning.Operation

    /// See `MemorystoreClient.createInstance`.
    func createInstance(withPolling: CreateInstanceRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Instance>

    /// See `MemorystoreClient.createInstance`.
    func createInstance(
      parent: Swift.String,
      instance: Instance?,
      instanceId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Instance>

    /// See `MemorystoreClient.updateInstance`.
    func updateInstance(request: UpdateInstanceRequest) async throws -> GoogleLongrunning.Operation

    /// See `MemorystoreClient.updateInstance`.
    func updateInstance(withPolling: UpdateInstanceRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Instance>

    /// See `MemorystoreClient.updateInstance`.
    func updateInstance(
      instance: Instance?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Instance>

    /// See `MemorystoreClient.deleteInstance`.
    func deleteInstance(request: DeleteInstanceRequest) async throws -> GoogleLongrunning.Operation

    /// See `MemorystoreClient.deleteInstance`.
    func deleteInstance(withPolling: DeleteInstanceRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Void>

    /// See `MemorystoreClient.deleteInstance`.
    func deleteInstance(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `MemorystoreClient.getCertificateAuthority`.
    func getCertificateAuthority(request: GetCertificateAuthorityRequest) async throws
      -> GoogleCloudMemorystoreV1.CertificateAuthority

    /// See `MemorystoreClient.getCertificateAuthority`.
    func getCertificateAuthority(
      name: Swift.String,
    ) async throws -> GoogleCloudMemorystoreV1.CertificateAuthority

    /// See `MemorystoreClient.getSharedRegionalCertificateAuthority`.
    func getSharedRegionalCertificateAuthority(
      request: GetSharedRegionalCertificateAuthorityRequest
    ) async throws -> GoogleCloudMemorystoreV1.SharedRegionalCertificateAuthority

    /// See `MemorystoreClient.getSharedRegionalCertificateAuthority`.
    func getSharedRegionalCertificateAuthority(
      name: Swift.String,
    ) async throws -> GoogleCloudMemorystoreV1.SharedRegionalCertificateAuthority

    /// See `MemorystoreClient.rescheduleMaintenance`.
    func rescheduleMaintenance(request: RescheduleMaintenanceRequest) async throws
      -> GoogleLongrunning.Operation

    /// See `MemorystoreClient.rescheduleMaintenance`.
    func rescheduleMaintenance(withPolling: RescheduleMaintenanceRequest) async throws
      -> any GoogleCloudGax.PollableOperation<Instance>

    /// See `MemorystoreClient.rescheduleMaintenance`.
    func rescheduleMaintenance(
      name: Swift.String,
      rescheduleType: RescheduleMaintenanceRequest.RescheduleType,
      scheduleTime: GoogleCloudWkt.Timestamp?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Instance>

    /// See `MemorystoreClient.listBackupCollections`.
    func listBackupCollections(request: ListBackupCollectionsRequest) async throws
      -> GoogleCloudMemorystoreV1.ListBackupCollectionsResponse

    /// See `MemorystoreClient.listBackupCollections`.
    func listBackupCollections(
      byItem: ListBackupCollectionsRequest
    ) throws -> any AsyncSequence<BackupCollection, Swift.Error>

    /// See `MemorystoreClient.listBackupCollections`.
    func listBackupCollections(
      parent: Swift.String,
    ) throws -> any AsyncSequence<BackupCollection, Swift.Error>

    /// See `MemorystoreClient.getBackupCollection`.
    func getBackupCollection(request: GetBackupCollectionRequest) async throws
      -> GoogleCloudMemorystoreV1.BackupCollection

    /// See `MemorystoreClient.getBackupCollection`.
    func getBackupCollection(
      name: Swift.String,
    ) async throws -> GoogleCloudMemorystoreV1.BackupCollection

    /// See `MemorystoreClient.listBackups`.
    func listBackups(request: ListBackupsRequest) async throws
      -> GoogleCloudMemorystoreV1.ListBackupsResponse

    /// See `MemorystoreClient.listBackups`.
    func listBackups(
      byItem: ListBackupsRequest
    ) throws -> any AsyncSequence<Backup, Swift.Error>

    /// See `MemorystoreClient.listBackups`.
    func listBackups(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Backup, Swift.Error>

    /// See `MemorystoreClient.getBackup`.
    func getBackup(request: GetBackupRequest) async throws -> GoogleCloudMemorystoreV1.Backup

    /// See `MemorystoreClient.getBackup`.
    func getBackup(
      name: Swift.String,
    ) async throws -> GoogleCloudMemorystoreV1.Backup

    /// See `MemorystoreClient.deleteBackup`.
    func deleteBackup(request: DeleteBackupRequest) async throws -> GoogleLongrunning.Operation

    /// See `MemorystoreClient.deleteBackup`.
    func deleteBackup(withPolling: DeleteBackupRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Void>

    /// See `MemorystoreClient.deleteBackup`.
    func deleteBackup(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `MemorystoreClient.exportBackup`.
    func exportBackup(request: ExportBackupRequest) async throws -> GoogleLongrunning.Operation

    /// See `MemorystoreClient.exportBackup`.
    func exportBackup(withPolling: ExportBackupRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Backup>

    /// See `MemorystoreClient.backupInstance`.
    func backupInstance(request: BackupInstanceRequest) async throws -> GoogleLongrunning.Operation

    /// See `MemorystoreClient.backupInstance`.
    func backupInstance(withPolling: BackupInstanceRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Instance>

    /// See `MemorystoreClient.backupInstance`.
    func backupInstance(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Instance>

    /// See `MemorystoreClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `MemorystoreClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `MemorystoreClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `MemorystoreClient.listOperations`.
    func listOperations(request: GoogleLongrunning.ListOperationsRequest) async throws
      -> GoogleLongrunning.ListOperationsResponse

    /// See `MemorystoreClient.listOperations`.
    func listOperations(
      byItem: GoogleLongrunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

    /// See `MemorystoreClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

    /// See `MemorystoreClient.deleteOperation`.
    func deleteOperation(request: GoogleLongrunning.DeleteOperationRequest) async throws

    /// See `MemorystoreClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `MemorystoreClient.cancelOperation`.
    func cancelOperation(request: GoogleLongrunning.CancelOperationRequest) async throws

    /// See `MemorystoreClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `MemorystoreClient.listInstances`.
    func listInstances(
      request: ListInstancesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMemorystoreV1.ListInstancesResponse

    /// See `MemorystoreClient.listInstances`.
    func listInstances(
      byItem: ListInstancesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Instance, Swift.Error>

    /// See `MemorystoreClient.getInstance`.
    func getInstance(
      request: GetInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMemorystoreV1.Instance

    /// See `MemorystoreClient.createInstance`.
    func createInstance(
      request: CreateInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `MemorystoreClient.createInstance`.
    func createInstance(
      withPolling: CreateInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Instance>

    /// See `MemorystoreClient.updateInstance`.
    func updateInstance(
      request: UpdateInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `MemorystoreClient.updateInstance`.
    func updateInstance(
      withPolling: UpdateInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Instance>

    /// See `MemorystoreClient.deleteInstance`.
    func deleteInstance(
      request: DeleteInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `MemorystoreClient.deleteInstance`.
    func deleteInstance(
      withPolling: DeleteInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `MemorystoreClient.getCertificateAuthority`.
    func getCertificateAuthority(
      request: GetCertificateAuthorityRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMemorystoreV1.CertificateAuthority

    /// See `MemorystoreClient.getSharedRegionalCertificateAuthority`.
    func getSharedRegionalCertificateAuthority(
      request: GetSharedRegionalCertificateAuthorityRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMemorystoreV1.SharedRegionalCertificateAuthority

    /// See `MemorystoreClient.rescheduleMaintenance`.
    func rescheduleMaintenance(
      request: RescheduleMaintenanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `MemorystoreClient.rescheduleMaintenance`.
    func rescheduleMaintenance(
      withPolling: RescheduleMaintenanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Instance>

    /// See `MemorystoreClient.listBackupCollections`.
    func listBackupCollections(
      request: ListBackupCollectionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMemorystoreV1.ListBackupCollectionsResponse

    /// See `MemorystoreClient.listBackupCollections`.
    func listBackupCollections(
      byItem: ListBackupCollectionsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<BackupCollection, Swift.Error>

    /// See `MemorystoreClient.getBackupCollection`.
    func getBackupCollection(
      request: GetBackupCollectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMemorystoreV1.BackupCollection

    /// See `MemorystoreClient.listBackups`.
    func listBackups(
      request: ListBackupsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMemorystoreV1.ListBackupsResponse

    /// See `MemorystoreClient.listBackups`.
    func listBackups(
      byItem: ListBackupsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Backup, Swift.Error>

    /// See `MemorystoreClient.getBackup`.
    func getBackup(
      request: GetBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMemorystoreV1.Backup

    /// See `MemorystoreClient.deleteBackup`.
    func deleteBackup(
      request: DeleteBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `MemorystoreClient.deleteBackup`.
    func deleteBackup(
      withPolling: DeleteBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `MemorystoreClient.exportBackup`.
    func exportBackup(
      request: ExportBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `MemorystoreClient.exportBackup`.
    func exportBackup(
      withPolling: ExportBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Backup>

    /// See `MemorystoreClient.backupInstance`.
    func backupInstance(
      request: BackupInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `MemorystoreClient.backupInstance`.
    func backupInstance(
      withPolling: BackupInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Instance>

    /// See `MemorystoreClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `MemorystoreClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `MemorystoreClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `MemorystoreClient.listOperations`.
    func listOperations(
      request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse

    /// See `MemorystoreClient.listOperations`.
    func listOperations(
      byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

    /// See `MemorystoreClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongrunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `MemorystoreClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.MemorystoreProtocol {
  public func listInstances(request: ListInstancesRequest) async throws
    -> GoogleCloudMemorystoreV1.ListInstancesResponse
  {
    try await self.listInstances(request: request, options: .init())
  }

  public func listInstances(
    request: ListInstancesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMemorystoreV1.ListInstancesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listInstances(
    byItem: ListInstancesRequest
  ) throws -> any AsyncSequence<Instance, Swift.Error> {
    try self.listInstances(byItem: byItem, options: .init())
  }

  public func listInstances(
    byItem: ListInstancesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Instance, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudMemorystoreV1.ListInstancesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listInstances(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Instance, Swift.Error> {
    let request = ListInstancesRequest().with {
      $0.parent = parent
    }
    return try self.listInstances(byItem: request)
  }

  public func getInstance(request: GetInstanceRequest) async throws
    -> GoogleCloudMemorystoreV1.Instance
  {
    try await self.getInstance(request: request, options: .init())
  }

  public func getInstance(
    request: GetInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMemorystoreV1.Instance {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getInstance(
    name: Swift.String,
  ) async throws -> GoogleCloudMemorystoreV1.Instance {
    let request = GetInstanceRequest().with {
      $0.name = name
    }
    return try await self.getInstance(request: request)
  }

  public func createInstance(request: CreateInstanceRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.createInstance(request: request, options: .init())
  }

  public func createInstance(
    request: CreateInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createInstance(withPolling: CreateInstanceRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Instance>
  {
    try await self.createInstance(withPolling: withPolling, options: .init())
  }

  public func createInstance(
    withPolling: CreateInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Instance> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Instance>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createInstance(
    parent: Swift.String,
    instance: Instance?,
    instanceId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Instance> {
    let request = CreateInstanceRequest().with {
      $0.parent = parent
      $0.instance = instance
      $0.instanceId = instanceId
    }
    return try await self.createInstance(withPolling: request)
  }

  public func updateInstance(request: UpdateInstanceRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.updateInstance(request: request, options: .init())
  }

  public func updateInstance(
    request: UpdateInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateInstance(withPolling: UpdateInstanceRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Instance>
  {
    try await self.updateInstance(withPolling: withPolling, options: .init())
  }

  public func updateInstance(
    withPolling: UpdateInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Instance> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Instance>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateInstance(
    instance: Instance?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Instance> {
    let request = UpdateInstanceRequest().with {
      $0.instance = instance
      $0.updateMask = updateMask
    }
    return try await self.updateInstance(withPolling: request)
  }

  public func deleteInstance(request: DeleteInstanceRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.deleteInstance(request: request, options: .init())
  }

  public func deleteInstance(
    request: DeleteInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteInstance(withPolling: DeleteInstanceRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Void>
  {
    try await self.deleteInstance(withPolling: withPolling, options: .init())
  }

  public func deleteInstance(
    withPolling: DeleteInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteInstance(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let request = DeleteInstanceRequest().with {
      $0.name = name
    }
    return try await self.deleteInstance(withPolling: request)
  }

  public func getCertificateAuthority(request: GetCertificateAuthorityRequest) async throws
    -> GoogleCloudMemorystoreV1.CertificateAuthority
  {
    try await self.getCertificateAuthority(request: request, options: .init())
  }

  public func getCertificateAuthority(
    request: GetCertificateAuthorityRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMemorystoreV1.CertificateAuthority {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getCertificateAuthority(
    name: Swift.String,
  ) async throws -> GoogleCloudMemorystoreV1.CertificateAuthority {
    let request = GetCertificateAuthorityRequest().with {
      $0.name = name
    }
    return try await self.getCertificateAuthority(request: request)
  }

  public func getSharedRegionalCertificateAuthority(
    request: GetSharedRegionalCertificateAuthorityRequest
  ) async throws -> GoogleCloudMemorystoreV1.SharedRegionalCertificateAuthority {
    try await self.getSharedRegionalCertificateAuthority(request: request, options: .init())
  }

  public func getSharedRegionalCertificateAuthority(
    request: GetSharedRegionalCertificateAuthorityRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMemorystoreV1.SharedRegionalCertificateAuthority {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getSharedRegionalCertificateAuthority(
    name: Swift.String,
  ) async throws -> GoogleCloudMemorystoreV1.SharedRegionalCertificateAuthority {
    let request = GetSharedRegionalCertificateAuthorityRequest().with {
      $0.name = name
    }
    return try await self.getSharedRegionalCertificateAuthority(request: request)
  }

  public func rescheduleMaintenance(request: RescheduleMaintenanceRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.rescheduleMaintenance(request: request, options: .init())
  }

  public func rescheduleMaintenance(
    request: RescheduleMaintenanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func rescheduleMaintenance(withPolling: RescheduleMaintenanceRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Instance>
  {
    try await self.rescheduleMaintenance(withPolling: withPolling, options: .init())
  }

  public func rescheduleMaintenance(
    withPolling: RescheduleMaintenanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Instance> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Instance>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func rescheduleMaintenance(
    name: Swift.String,
    rescheduleType: RescheduleMaintenanceRequest.RescheduleType,
    scheduleTime: GoogleCloudWkt.Timestamp?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Instance> {
    let request = RescheduleMaintenanceRequest().with {
      $0.name = name
      $0.rescheduleType = rescheduleType
      $0.scheduleTime = scheduleTime
    }
    return try await self.rescheduleMaintenance(withPolling: request)
  }

  public func listBackupCollections(request: ListBackupCollectionsRequest) async throws
    -> GoogleCloudMemorystoreV1.ListBackupCollectionsResponse
  {
    try await self.listBackupCollections(request: request, options: .init())
  }

  public func listBackupCollections(
    request: ListBackupCollectionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMemorystoreV1.ListBackupCollectionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listBackupCollections(
    byItem: ListBackupCollectionsRequest
  ) throws -> any AsyncSequence<BackupCollection, Swift.Error> {
    try self.listBackupCollections(byItem: byItem, options: .init())
  }

  public func listBackupCollections(
    byItem: ListBackupCollectionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<BackupCollection, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudMemorystoreV1.ListBackupCollectionsResponse
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listBackupCollections(
    parent: Swift.String,
  ) throws -> any AsyncSequence<BackupCollection, Swift.Error> {
    let request = ListBackupCollectionsRequest().with {
      $0.parent = parent
    }
    return try self.listBackupCollections(byItem: request)
  }

  public func getBackupCollection(request: GetBackupCollectionRequest) async throws
    -> GoogleCloudMemorystoreV1.BackupCollection
  {
    try await self.getBackupCollection(request: request, options: .init())
  }

  public func getBackupCollection(
    request: GetBackupCollectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMemorystoreV1.BackupCollection {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getBackupCollection(
    name: Swift.String,
  ) async throws -> GoogleCloudMemorystoreV1.BackupCollection {
    let request = GetBackupCollectionRequest().with {
      $0.name = name
    }
    return try await self.getBackupCollection(request: request)
  }

  public func listBackups(request: ListBackupsRequest) async throws
    -> GoogleCloudMemorystoreV1.ListBackupsResponse
  {
    try await self.listBackups(request: request, options: .init())
  }

  public func listBackups(
    request: ListBackupsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMemorystoreV1.ListBackupsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listBackups(
    byItem: ListBackupsRequest
  ) throws -> any AsyncSequence<Backup, Swift.Error> {
    try self.listBackups(byItem: byItem, options: .init())
  }

  public func listBackups(
    byItem: ListBackupsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Backup, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudMemorystoreV1.ListBackupsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listBackups(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Backup, Swift.Error> {
    let request = ListBackupsRequest().with {
      $0.parent = parent
    }
    return try self.listBackups(byItem: request)
  }

  public func getBackup(request: GetBackupRequest) async throws -> GoogleCloudMemorystoreV1.Backup {
    try await self.getBackup(request: request, options: .init())
  }

  public func getBackup(
    request: GetBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMemorystoreV1.Backup {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getBackup(
    name: Swift.String,
  ) async throws -> GoogleCloudMemorystoreV1.Backup {
    let request = GetBackupRequest().with {
      $0.name = name
    }
    return try await self.getBackup(request: request)
  }

  public func deleteBackup(request: DeleteBackupRequest) async throws -> GoogleLongrunning.Operation
  {
    try await self.deleteBackup(request: request, options: .init())
  }

  public func deleteBackup(
    request: DeleteBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteBackup(withPolling: DeleteBackupRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Void>
  {
    try await self.deleteBackup(withPolling: withPolling, options: .init())
  }

  public func deleteBackup(
    withPolling: DeleteBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteBackup(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let request = DeleteBackupRequest().with {
      $0.name = name
    }
    return try await self.deleteBackup(withPolling: request)
  }

  public func exportBackup(request: ExportBackupRequest) async throws -> GoogleLongrunning.Operation
  {
    try await self.exportBackup(request: request, options: .init())
  }

  public func exportBackup(
    request: ExportBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func exportBackup(withPolling: ExportBackupRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Backup>
  {
    try await self.exportBackup(withPolling: withPolling, options: .init())
  }

  public func exportBackup(
    withPolling: ExportBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Backup> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Backup>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func backupInstance(request: BackupInstanceRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.backupInstance(request: request, options: .init())
  }

  public func backupInstance(
    request: BackupInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func backupInstance(withPolling: BackupInstanceRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Instance>
  {
    try await self.backupInstance(withPolling: withPolling, options: .init())
  }

  public func backupInstance(
    withPolling: BackupInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Instance> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Instance>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func backupInstance(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Instance> {
    let request = BackupInstanceRequest().with {
      $0.name = name
    }
    return try await self.backupInstance(withPolling: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongrunning.ListOperationsRequest) async throws
    -> GoogleLongrunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongrunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongrunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let request = GoogleLongrunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongrunning.GetOperationRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongrunning.Operation {
    let request = GoogleLongrunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongrunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongrunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongrunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongrunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongrunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
