// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol MemorystoreStub: Sendable {
    func listInstances(
      request: ListInstancesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.ListInstancesResponse

    func getInstance(
      request: GetInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.Instance

    func createInstance(
      request: CreateInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateInstance(
      request: UpdateInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteInstance(
      request: DeleteInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getCertificateAuthority(
      request: GetCertificateAuthorityRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.CertificateAuthority

    func getSharedRegionalCertificateAuthority(
      request: GetSharedRegionalCertificateAuthorityRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.SharedRegionalCertificateAuthority

    func rescheduleMaintenance(
      request: RescheduleMaintenanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listBackupCollections(
      request: ListBackupCollectionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.ListBackupCollectionsResponse

    func getBackupCollection(
      request: GetBackupCollectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.BackupCollection

    func listBackups(
      request: ListBackupsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.ListBackupsResponse

    func getBackup(
      request: GetBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.Backup

    func deleteBackup(
      request: DeleteBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func exportBackup(
      request: ExportBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func backupInstance(
      request: BackupInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func startMigration(
      request: StartMigrationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func finishMigration(
      request: FinishMigrationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listTokenAuthUsers(
      request: ListTokenAuthUsersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.ListTokenAuthUsersResponse

    func getTokenAuthUser(
      request: GetTokenAuthUserRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.TokenAuthUser

    func listAuthTokens(
      request: ListAuthTokensRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.ListAuthTokensResponse

    func getAuthToken(
      request: GetAuthTokenRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMemoryStoreV1.AuthToken

    func addTokenAuthUser(
      request: AddTokenAuthUserRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteTokenAuthUser(
      request: DeleteTokenAuthUserRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func addAuthToken(
      request: AddAuthTokenRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteAuthToken(
      request: DeleteAuthTokenRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
