// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Configuration for the migration of an instance.
public struct MigrationConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. Migration state of the instance.
  public var state: MigrationConfig.State = MigrationConfig.State()

  /// Output only. Represents a boolean flag to force migration finalization
  /// without offset catch up validation between source and target before
  /// stopping replication.
  public var forceFinishMigration: Swift.Bool = Swift.Bool()

  /// Details about the migration source.
  public var source: OneOf_Source? = nil

  /// Initialize a new instance of `MigrationConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MigrationConfig().with { $0.selfManagedSource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case selfManagedSource = "selfManagedSource"
    case state = "state"
    case forceFinishMigration = "forceFinishMigration"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.state = try container.decode(MigrationConfig.State.self, forKey: .state)
    self.forceFinishMigration = try container.decode(Swift.Bool.self, forKey: .forceFinishMigration)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let selfManagedSource = try container.decodeIfPresent(
      SelfManagedSource?.self, forKey: .selfManagedSource)
    {
      try sourceCheckAndSet(.selfManagedSource(selfManagedSource))
    }
    self.source = source
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.forceFinishMigration, forKey: .forceFinishMigration)

    if let choice = self.source {
      switch choice {
      case .selfManagedSource(let value):
        try container.encode(value, forKey: .selfManagedSource)
      }
    }
  }

  /// Migration state of the instance.
  /// New values may be added in the future.
  public enum State: Codable, Equatable, Sendable {
    /// Instance has no migration related activity. This is the initial state.
    case unspecified
    /// Instance is not currently migrating. The instance underwent a migration
    /// attempt that failed, and the subsequent rollback was successful. The
    /// instance is now ready for a new migration attempt if desired.
    case rolledBack
    /// Instance is successfully migrated.
    case migrated
    /// Indicates a previous migration attempt failed. The high-level instance
    /// state will be `MIGRATING`. The instance is not ready for a new migration
    /// attempt. Rollback is in progress to restore the instance to its original
    /// state. The instance will remain in this state until rollback is
    /// successful.
    case rollingBack
    /// Instance is in the process of migration. Instance has established
    /// successful replication and is ready for cutover.
    case replicationEstablished
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .rolledBack: return 1
      case .migrated: return 4
      case .rollingBack: return 5
      case .replicationEstablished: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .rolledBack: return "ROLLED_BACK"
      case .migrated: return "MIGRATED"
      case .rollingBack: return "ROLLING_BACK"
      case .replicationEstablished: return "REPLICATION_ESTABLISHED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ROLLED_BACK": self = .rolledBack
      case "ROLLING_BACK": self = .rollingBack
      case "REPLICATION_ESTABLISHED": self = .replicationEstablished
      case "MIGRATED": self = .migrated
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .rolledBack
      case 4: self = .migrated
      case 5: self = .rollingBack
      case 6: self = .replicationEstablished
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .rolledBack: return try container.encode(1)
      case .migrated: return try container.encode(4)
      case .rollingBack: return try container.encode(5)
      case .replicationEstablished: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Details about the migration source.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// Output only. Configuration for migrating from a self-managed Valkey/Redis
    /// instance
    indirect case selfManagedSource(SelfManagedSource?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.memorystore.v1.MigrationConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
