// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Details of consumer resources in a PSC connection.
public struct PscAutoConnection: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The PSC connection id of the forwarding rule connected to the
  /// service attachment.
  public var pscConnectionId: Swift.String = Swift.String()

  /// Output only. The IP allocated on the consumer network for the PSC
  /// forwarding rule.
  public var ipAddress: Swift.String = Swift.String()

  /// Output only. The URI of the consumer side forwarding rule.
  /// Format:
  /// projects/{project}/regions/{region}/forwardingRules/{forwarding_rule}
  public var forwardingRule: Swift.String = Swift.String()

  /// Required. The consumer project_id where PSC connections are established.
  /// This should be the same project_id that the instance is being created in.
  public var projectId: Swift.String = Swift.String()

  /// Required. The network where the PSC endpoints are created, in the form of
  /// projects/{project_id}/global/networks/{network_name}.
  public var network: Swift.String = Swift.String()

  /// Output only. The service attachment which is the target of the PSC
  /// connection, in the form of
  /// projects/{project-id}/regions/{region}/serviceAttachments/{service-attachment-id}.
  public var serviceAttachment: Swift.String = Swift.String()

  /// Output only. The status of the PSC connection: whether a connection exists
  /// and ACTIVE or it no longer exists. Please note that this value is updated
  /// periodically. Please use Private Service Connect APIs for the latest
  /// status.
  public var pscConnectionStatus: PscConnectionStatus = PscConnectionStatus()

  /// Output only. Type of the PSC connection.
  public var connectionType: ConnectionType = ConnectionType()

  /// Ports of the exposed endpoint.
  public var ports: OneOf_Ports? = nil

  /// Initialize a new instance of `PscAutoConnection`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PscAutoConnection().with { $0.port = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case port = "port"
    case pscConnectionId = "pscConnectionId"
    case ipAddress = "ipAddress"
    case forwardingRule = "forwardingRule"
    case projectId = "projectId"
    case network = "network"
    case serviceAttachment = "serviceAttachment"
    case pscConnectionStatus = "pscConnectionStatus"
    case connectionType = "connectionType"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.pscConnectionId = try container.decode(Swift.String.self, forKey: .pscConnectionId)
    self.ipAddress = try container.decode(Swift.String.self, forKey: .ipAddress)
    self.forwardingRule = try container.decode(Swift.String.self, forKey: .forwardingRule)
    self.projectId = try container.decode(Swift.String.self, forKey: .projectId)
    self.network = try container.decode(Swift.String.self, forKey: .network)
    self.serviceAttachment = try container.decode(Swift.String.self, forKey: .serviceAttachment)
    self.pscConnectionStatus = try container.decode(
      PscConnectionStatus.self, forKey: .pscConnectionStatus)
    self.connectionType = try container.decode(ConnectionType.self, forKey: .connectionType)

    var ports: OneOf_Ports? = nil
    let portsCheckAndSet = {
      if ports != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'ports'"))
      }
      ports = $0
    }
    if let port = try container.decodeIfPresent(Swift.Int32.self, forKey: .port) {
      try portsCheckAndSet(.port(port))
    }
    self.ports = ports
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.pscConnectionId, forKey: .pscConnectionId)
    try container.encode(self.ipAddress, forKey: .ipAddress)
    try container.encode(self.forwardingRule, forKey: .forwardingRule)
    try container.encode(self.projectId, forKey: .projectId)
    try container.encode(self.network, forKey: .network)
    try container.encode(self.serviceAttachment, forKey: .serviceAttachment)
    try container.encode(self.pscConnectionStatus, forKey: .pscConnectionStatus)
    try container.encode(self.connectionType, forKey: .connectionType)

    if let choice = self.ports {
      switch choice {
      case .port(let value):
        try container.encode(value, forKey: .port)
      }
    }
  }

  /// Ports of the exposed endpoint.
  public enum OneOf_Ports: Codable, Equatable, Sendable {
    /// Optional. port will only be set for Primary/Reader or Discovery endpoint.
    case port(Swift.Int32)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.memorystore.v1.PscAutoConnection"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
