// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Details of the self-managed source instance.
public struct SelfManagedSource: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The IP address of the source instance.
  /// This IP address should be a stable IP address that can be accessed by the
  /// Memorystore instance throughout the migration process.
  public var ipAddress: Swift.String = Swift.String()

  /// Required. The port of the source instance.
  /// This port should be a stable port that can be accessed by the Memorystore
  /// instance throughout the migration process.
  public var port: Swift.Int32 = Swift.Int32()

  /// Required. The resource name of the Private Service Connect Network
  /// Attachment used to establish connectivity to the source instance. This
  /// network attachment has the following requirements:
  /// 1. It must be in the same project as the Memorystore instance.
  /// 2. It must be in the same region as the Memorystore instance.
  /// 3. The subnet attached to the network attachment must be in the same VPC
  /// network as the source instance nodes.
  ///
  /// Format:
  /// projects/{project}/regions/{region}/networkAttachments/{network_attachment}
  public var networkAttachment: Swift.String = Swift.String()

  /// Initialize a new instance of `SelfManagedSource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SelfManagedSource().with { $0.ipAddress = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.memorystore.v1.SelfManagedSource"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
